--- #YAML:1.0
name:               List-Analyse-Sequence-Analyser-OL-RomanNumerals
version:            0.01
abstract:           Find Roman numeral sequences.
author:
    - Alastair Douglas <altreus@perl.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::Util:  0
    Roman:       0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
